---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: broadcaster-secrets
spec:
  encryptedData:
    telegram_bot_token: AgCvN9MTE0CNH8ZiDVwDk8Fjy/gYxhBM0ZV15P89c4dpX2aBJvj38O8Z2mScsjH65AgXHixvqSQXUQ5lxm6gMr7E/SA6SKZR7NR+e30Oxb5z32NdD6EsFIOrFTFEt3GHuejf75TJTmec4CtxaxvVP+wuBtagEFs/wQRRUsrvJoXdWXtCWOawhSQjP0J60wyT771cyoY7SGZNHFv1/NbyLbBYEPr4cE9XrQkWrnBXsFVEuu+tQqyI6b19ClkHqngTcyeUlJVlY8TmrtjHAizZhdTW3w1bxPF4fliwUIpn7Hb3GDh1My5bxJg8W8cht4UVL0t+8uK8p3AdOFQwaKY4H1gEMAlULhuEa+tXy/eLEFIYxXyCtbFvrQlTIgfAEmk7tVaAlQC4LcdYJ6FfqXJEdddOM9XQbgowmsiqFxlLH5uxA/qVRMvHGqHFhRTiDMO2w5tMRjaYf76eQ05JSyfPenmimKbqPH9iuRrQ44qh8gHfpZZ/P2nqgA5oPI5wPW612qo03NQjH6++VjAIhNqch6SmrT6/NCAS2wASiMrFPAcl46rQ+3+A4YgQ2jGormqKxvuvTAfpqivawq80uHdUE2YTVsqZsR9gQpCZGANwX30EUM3ZQryWQkdM7omGnfR74IerFLtoq3HZDaK+iSw6+pdnge9tLVoS3D3vw9Bo6Hkt2C8j1plyCG5VZSXvqzrTH1usRHoODAK9CS78IaFOfH4udf+RHMlkd3muNXRsI1pqi/7hkD2x3Izv4w7qGGQE
  template:
    metadata:
      creationTimestamp: null
      name: broadcaster-secrets
