apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kottinov/tkt-21027.git
    targetRevision: main
    path: project/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
